apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: backup-many
spec:
  concurrencyPolicy: Forbid
  # every day at 01:05
  schedule: '5 1 * * *'
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        parent: backup-many
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - bash
            args:
            - -c
            - source /srv/${WP_ENV}/venv/bin/activate && export PYTHONPATH=/srv/${WP_ENV}/jahia2wp/src && cd /srv/${WP_ENV}/jahia2wp && set -o allexport && source .env && set +o allexport && python src/jahia2wp.py backup-many /srv/data.csv
            env:
            - name: WP_ENV
              value: subdomains
            image: docker-registry.default.svc:5000/wwp/cronjob:latest
            imagePullPolicy: Always
            name: inventory
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /srv
              name: wordpress
            - mountPath: /backups
              name: backups
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: wwp 
          serviceAccountName: wwp
          terminationGracePeriodSeconds: 30
          volumes:
          - name: wordpress
            persistentVolumeClaim:
              claimName: wordpress-0
          - name: backups
            persistentVolumeClaim:
              claimName: backups-0
