# These targets are to be run from Camp2Camp infrastructure
.PHONY: bootstrap-c2c
ifndef WP_ENV
	$(error WP_ENV is undefined)
endif

bootstrap-c2c :
	cd /srv/${WP_ENV} && virtualenv -p `which python3` venv
	. /srv/${WP_ENV}/venv/bin/activate \
	  && export PYTHONPATH=/srv/${WP_ENV}/jahia2wp/src \
	  && pip install -r requirements/local.txt
