# Ansible playbook for WordPress deployments

# "hosts" are not really hosts; rather, they are WordPress instances
# See the list in hosts/wordpress-instances
- hosts: all-wordpresses
  gather_facts: no   # Delayed, see below
  pre_tasks:
    - name: Ansible pre-configuration
      set_fact:
        ansible_user: www-data
        ansible_python_interpreter: "/srv/{{wp_env}}/venv/bin/python"
    - name: Create and use remote temporary directory (if required)
      include_tasks: '{{ "../tasks/remote-tempdir.yml" if play_dump is not defined else "../tasks/noop.yml" }}'
    - name: Gathering facts (delayed after Ansible pre-configuration)
      setup:
  roles:
    - { role: ../roles/wordpress }
