#!/bin/sh
#
# This is an Ansible playbook to do or redo all the things.
#
#
# Usage: this script expects to be invoked from the top
#        of the source tree.
#
# ./ansible/deploy
#
# ./ansible/deploy -l charte-wp-dcsl
#
#
# If you are unfamiliar with Ansible, read up on it at
# - https://www.ansible.com/overview/how-ansible-works
# - https://github.com/jdauphant/awesome-ansible

inventories="-i ansible/hosts-dev"
case "$1" in
    --prod)
        inventories="$inventories -i ansible/hosts-prod" ;;
esac

thisdir="$(dirname "$(realpath "$0")")"

ansible-playbook -e "play_create_or_restore=true" -e "play_update=true" $inventories "$@" "$thisdir"/playbooks/wordpress-main.yml
