#!/bin/sh
#
# This is an Ansible playbook to do or redo all the things.
#
#
# Usage: this script expects to be invoked from the top
#        of the source tree.
#
# ./ansible/deploy
#
# ./ansible/deploy -l charte-wp-dcsl
#
#
# If you are unfamiliar with Ansible, read up on it at
# - https://www.ansible.com/overview/how-ansible-works
# - https://github.com/jdauphant/awesome-ansible


ansible-playbook -e "play_create_or_restore=true" -i ansible/hosts-dev "$@" ansible/playbooks/wordpress-main.yml
